### ISSUE TITLE
rootwizard stays in front of dropdowns

### ISSUE THREAD

**Issue by tchoulihan** [VinceG/twitter-bootstrap-wizard#129]
Not sure why, but rootwizard always renders in front of dropdown menus. I've tried changing the z-index  on .nav, .navbar, .dropdown, and .dropdown menu's, to no avail.

**Comment by tchoulihan** [comment]
I've found that this code fixes it, if its any help:
```css
.dropdown, .dropdown-menu {
  z-index:2;
}
.navbar {
  position: static;
  z-index: 1;
}
```
